from setuptools import setup

setup(
    name='AudioTagger',
    version='v1.0',
    packages=['venv.lib.python3.6.site-packages.past', 'venv.lib.python3.6.site-packages.past.tests',
              'venv.lib.python3.6.site-packages.past.types', 'venv.lib.python3.6.site-packages.past.utils',
              'venv.lib.python3.6.site-packages.past.builtins', 'venv.lib.python3.6.site-packages.past.translation',
              'venv.lib.python3.6.site-packages.PyQt5', 'venv.lib.python3.6.site-packages.PyQt5.uic',
              'venv.lib.python3.6.site-packages.PyQt5.uic.Loader', 'venv.lib.python3.6.site-packages.PyQt5.uic.port_v2',
              'venv.lib.python3.6.site-packages.PyQt5.uic.port_v3',
              'venv.lib.python3.6.site-packages.PyQt5.uic.Compiler', 'venv.lib.python3.6.site-packages.future',
              'venv.lib.python3.6.site-packages.future.moves', 'venv.lib.python3.6.site-packages.future.moves.dbm',
              'venv.lib.python3.6.site-packages.future.moves.html',
              'venv.lib.python3.6.site-packages.future.moves.http',
              'venv.lib.python3.6.site-packages.future.moves.test',
              'venv.lib.python3.6.site-packages.future.moves.urllib',
              'venv.lib.python3.6.site-packages.future.moves.xmlrpc',
              'venv.lib.python3.6.site-packages.future.moves.tkinter', 'venv.lib.python3.6.site-packages.future.tests',
              'venv.lib.python3.6.site-packages.future.types', 'venv.lib.python3.6.site-packages.future.utils',
              'venv.lib.python3.6.site-packages.future.builtins', 'venv.lib.python3.6.site-packages.future.backports',
              'venv.lib.python3.6.site-packages.future.backports.html',
              'venv.lib.python3.6.site-packages.future.backports.http',
              'venv.lib.python3.6.site-packages.future.backports.test',
              'venv.lib.python3.6.site-packages.future.backports.email',
              'venv.lib.python3.6.site-packages.future.backports.email.mime',
              'venv.lib.python3.6.site-packages.future.backports.urllib',
              'venv.lib.python3.6.site-packages.future.backports.xmlrpc',
              'venv.lib.python3.6.site-packages.future.standard_library', 'venv.lib.python3.6.site-packages.screen',
              'venv.lib.python3.6.site-packages.desktop', 'venv.lib.python3.6.site-packages.qstring',
              'venv.lib.python3.6.site-packages.libfuturize', 'venv.lib.python3.6.site-packages.libfuturize.fixes',
              'venv.lib.python3.6.site-packages.libpasteurize', 'venv.lib.python3.6.site-packages.libpasteurize.fixes',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip.req',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip.vcs',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip.utils',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip.compat',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip.models',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.idna',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.certifi',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.chardet',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.chardet.cli',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.urllib3',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.urllib3.util',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip.commands',
              'venv.lib.python3.6.site-packages.pip-9.0.3-py3.6.egg.pip.operations'],
    url='https://github.com/gerwis1998/AudioTagger',
    license='GPL - 3.0',
    author='gerard',
    author_email='gerwis1998@gmail.com',
    description='Tagger for audio files'
)
